set shell := ["zsh", "-uc"]

default_server_port := "47111"
godot_bin := "${GODOT_BIN:-/Applications/Godot.app/Contents/MacOS/Godot}"
gdlint_bin := "${GDLINT_BIN:-/Users/yan/Library/Python/3.12/bin/gdlint}"
gdformat_bin := "${GDFORMAT_BIN:-/Users/yan/Library/Python/3.12/bin/gdformat}"

build-dry:
	{{godot_bin}} --headless --verbose --path . --quit

refresh-cache:
	TMP_HOME=$(mktemp -d); HOME="$TMP_HOME" {{godot_bin}} --headless --import --quit --path .

server-local port=default_server_port:
	{{godot_bin}} --headless --path . -- --server --port={{port}}

lint:
	{{gdlint_bin}} .

fmt-check:
	{{gdformat_bin}} . --check

fmt:
	{{gdformat_bin}} .

fix: refresh-cache build-dry fmt lint

apk-install:
	adb install -r dist/android/Ironfront.apk

apk-export:
	mkdir -p dist/android
	{{godot_bin}} --headless --path . --export-release "Android APK" dist/android/Ironfront.apk
